name: Lint

on: [push, pull_request]

jobs:
  fmt:
    name: "cargo fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.34.2
          components: rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: "cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.34.2
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          args: --all-features
